apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: do-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    access-token: AgATqwtYk4/FOvD/pe96LerXsLGsiehIdkYl91eQd/drwheyOFecZLZWzhmTsk2IsoT/cu+XlJkECe5gdvsoqXsfen0TIEbWhy5zv5w1wrUXhZspv5TyXzQtIlIxozHu9TMgJH2HsPpAFqyIaqzzUxO9p5cVrsRefmFyZ/q7DhYZQFKBgn9TtyI3eC7jDAEW3NLVX4obitYUVk8+sBfBiDcZSL8+wTnDcPqthMajcNf/e4G2MGI2ou088U70j1+Py05AqysvvXmG6VBq6Kij52WWy7mxdibergQ8RBSG4oCSydO2beM6+R9DmnBUiQA6TXL0tztCvawddAX6AQpw1sH4zybMLsyYVavTRT7iQrwQnHHS56tPU14SaEuL6zJv8bxeugh4OXbc5UvMbxejdB61bxQOZ9zFTvVYREoyCtDJDU6QLs4xxZ2a2mNskspyHm3o+oOW9xU16YzBR05JEHe0//4SwLpiiGgrDrEyJMQIMpgP3egvirkJKs0Ao5CuqDU5f+U5eJFT8NbtqN3JjPVIgqwI261zY+VGr4pvTJH5eGrnIFSISXN7UZ5oVv995WbnPZ3ZZVN7s8qsKDoBUT60JQJbgfHW1Z+YjxvSW/Xm6oTzr6rz+8oRHOH7/W2jmk52HUcdYDdbzzyxbQeNRgCJsOBUTbYDuT7rDXIZ0etYpu3KnA0R2rC2bMS0CGw45xj6MCBISqGuRQsKo4+5BIYCXrREfqWRLadzHGS31sLrtnEIPX+sF2YXk7e7FIYj4jF4XkJ/x/2KIwrdU4rRm8kZ7vyy0USeuQ==
  template:
    metadata:
      name: do-api-token-secret
      namespace: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-issuer
 namespace: argocd
spec:
 acme:
   email: services@carbonbits.co.ke
   # We use the staging server here for testing to avoid hitting
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: letsencrypt-issuer-account-key
   solvers:
     - dns01:
         digitalocean:
           tokenSecretRef:
             name: do-api-token-secret
             key: access-token