namespace: argocd

image:
  repository: carbonbits/agin-core:0.0.6
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.0.5

ingress:
  host: api.agin.cloud
  ingressClassName: contour

autoscaling:
  cpu: 0.25
  memory: 0.25Gi
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
