namespace: argocd

image:
  repository: carbonbits/agin-core
  pullPolicy: IfNotPresent

ingress:
  host: api.agin.cloud
  ingressClassName: contour

autoscaling:
  cpu: 0.25
  memory: 0.25Gi
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
