apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-service
  name: {{ .Chart.Name }}-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  type: ClusterIP