apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  revisionHistoryLimit: 5
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: {{ .Values.image.repository }}
          # resources:
          #   limits:
          #     cpu: {{ .Values.autoscaling.cpu }}
          #     memory: {{ .Values.autoscaling.memory }}
          #   requests:
          #     cpu: {{ .Values.autoscaling.cpu }}
          #     memory: {{ .Values.autoscaling.memory }}
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
          env:
          - name: APP_DATABASE
            value: {{ .Chart.Name }}
      imagePullSecrets:
        - name: dockerhub-carbonbits-credentials