apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-service
  name: {{ .Chart.Name }}-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: {{ .Chart.Name }}-deployment
  type: ClusterIP