apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agin-api-core
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/v0/run/agin-api-core
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true