namespace: argocd

image:
  repository: carbonbits/paylogic-core
  pullPolicy: IfNotPresent

ingress:
  host: paylogic-api-v1.carbonbits.co.ke
  ingressClassName: contour

autoscaling:
  cpu: 0.25
  memory: 0.25Gi
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
